update delete artifact step

diff --git a/.github/workflows/bdd-to-pages.yml b/.github/workflows/bdd-to-pages.yml
--- a/.github/workflows/bdd-to-pages.yml
+++ b/.github/workflows/bdd-to-pages.yml
@@ -50,19 +50,26 @@ jobs:
       - name: Run simple BDD test
         run: |
           source .venv/bin/activate
-          output=$(behave \
+          behave \
             --verbose \
             --tags=@simple \
             --format=allure_behave.formatter:AllureFormatter \
             --summary \
             --outfile $TEST_RESULTS_DIR \
-            --include simple 2>&1) || behave_exit_code=$?
-          important_line=$(echo "$output" | grep -o '[0-9]* features passed.*')
-          if [ "$behave_exit_code" -eq 0 ]; then
-            echo "::notice::${important_line}"
-          else
-            echo "::error::${important_line}"
-          fi
+            --include simple
+#          output=$(behave \
+#            --verbose \
+#            --tags=@simple \
+#            --format=allure_behave.formatter:AllureFormatter \
+#            --summary \
+#            --outfile $TEST_RESULTS_DIR \
+#            --include simple 2>&1) || behave_exit_code=$?
+#          important_line=$(echo "$output" | grep -o '[0-9]* features passed.*')
+#          if [ "$behave_exit_code" -eq 0 ]; then
+#            echo "::notice::${important_line}"
+#          else
+#            echo "::error::${important_line}"
+#          fi
         continue-on-error: true
 
 
