update combine allure file

diff --git a/.github/workflows/second-email-flow.yml b/.github/workflows/second-email-flow.yml
--- a/.github/workflows/second-email-flow.yml
+++ b/.github/workflows/second-email-flow.yml
@@ -26,9 +26,20 @@ jobs:
           tar -zxvf allure-2.23.1.tgz
           sudo mv allure-2.23.1 /opt/allure
           sudo ln -s /opt/allure/bin/allure /usr/bin/allure
+          allure --version
+          if [ "$?" -eq 0 ]; then
+            echo "Allure has been installed successfully."
+          else:
+            echo "Allure was unable to be installed successfully."
+          fi
 
-      - name: Check if Allure is installed
-        run: allure --version
+      - name: Cache pip3 dependencies
+        uses: actions/cache@v3
+        with:
+          path: ~/.cache/pip3
+          key: ${{ runner.os }}-pip3-${{ hashFiles('requirements.txt') }}
+          restore-keys: |
+            ${{ runner.os }}-pip3-
 
       - name: Install dependencies
         run: |
